/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-bright": "#f8f9ff",
        "on-surface": "#0b1c30",
        "on-tertiary": "#ffffff",
        "primary": "#004ac6",
        "inverse-surface": "#213145",
        "on-secondary-fixed-variant": "#3f465c",
        "surface-variant": "#d3e4fe",
        "surface-container": "#e5eeff",
        "secondary-fixed": "#dae2fd",
        "secondary-container": "#dae2fd",
        "on-tertiary-fixed-variant": "#005236",
        "on-primary": "#ffffff",
        "on-primary-container": "#eeefff",
        "surface-container-lowest": "#ffffff",
        "on-secondary-fixed": "#131b2e",
        "tertiary-fixed": "#6ffbbe",
        "on-secondary": "#ffffff",
        "primary-fixed": "#dbe1ff",
        "on-primary-fixed": "#00174b",
        "outline": "#737686",
        "on-surface-variant": "#434655",
        "background": "#f8f9ff",
        "surface": "#f8f9ff",
        "on-background": "#0b1c30",
        "surface-tint": "#0053db",
        "surface-container-high": "#dce9ff",
        "error-container": "#ffdad6",
        "inverse-primary": "#b4c5ff",
        "on-error-container": "#93000a",
        "secondary": "#565e74",
        "tertiary": "#006242",
        "error": "#ba1a1a",
        "tertiary-fixed-dim": "#4edea3",
        "primary-container": "#2563eb",
        "secondary-fixed-dim": "#bec6e0",
        "inverse-on-surface": "#eaf1ff",
        "primary-fixed-dim": "#b4c5ff",
        "tertiary-container": "#007d55",
        "surface-container-low": "#eff4ff",
        "on-tertiary-container": "#bdffdb",
        "surface-dim": "#cbdbf5",
        "on-primary-fixed-variant": "#003ea8",
        "outline-variant": "#c3c6d7",
        "surface-container-highest": "#d3e4fe",
        "on-tertiary-fixed": "#002113",
        "on-secondary-container": "#5c647a",
        "on-error": "#ffffff"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "space-2xl": "3rem",
        "gutter-desktop": "1.5rem",
        "margin-tablet": "1.5rem",
        "space-xs": "0.25rem",
        "space-xl": "2rem",
        "space-base": "1rem",
        "gutter": "1rem",
        "space-md": "0.75rem",
        "margin": "1rem",
        "space-lg": "1.5rem",
        "margin-desktop": "2rem",
        "space-2xs": "0.125rem",
        "space-sm": "0.5rem"
      },
      fontFamily: {
        "display": ["Manrope", "sans-serif"],
        "caption": ["Inter", "sans-serif"],
        "headline-lg": ["Manrope", "sans-serif"],
        "metric-stat": ["'JetBrains Mono'", "monospace"],
        "headline-sm": ["Manrope", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "headline-md": ["Manrope", "sans-serif"],
        "headline-lg-mobile": ["Manrope", "sans-serif"],
        "label-code": ["'JetBrains Mono'", "monospace"],
        "body-lg": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "display-mobile": ["Manrope", "sans-serif"]
      },
      fontSize: {
        "display": ["36px", { "lineHeight": "44px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "caption": ["11px", { "lineHeight": "14px", "letterSpacing": "0.02em", "fontWeight": "500" }],
        "headline-lg": ["30px", { "lineHeight": "38px", "letterSpacing": "-0.015em", "fontWeight": "600" }],
        "metric-stat": ["20px", { "lineHeight": "24px", "fontWeight": "600" }],
        "headline-sm": ["18px", { "lineHeight": "24px", "fontWeight": "600" }],
        "body-md": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
        "headline-md": ["22px", { "lineHeight": "28px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "headline-lg-mobile": ["24px", { "lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "label-code": ["13px", { "lineHeight": "18px", "fontWeight": "500" }],
        "body-lg": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "body-sm": ["12px", { "lineHeight": "16px", "fontWeight": "400" }],
        "display-mobile": ["28px", { "lineHeight": "36px", "letterSpacing": "-0.015em", "fontWeight": "700" }]
      }
    }
  },
  plugins: [],
}
